# <font color = 'dodgerblue'>**Introduction to Pandas**
Pandas is a powerful library for data manipulation and analysis in Python. It provides two main data structures: Series and Dataframes. In this crash course, we'll explore these foundational concepts through hands-on exercises.

## <font color = 'dodgerblue'>**Importing Pandas**
Let's start by importing Pandas.

In [4]:
import pandas as pd

## <font color = 'dodgerblue'>**Creating Pandas Series**
A Pandas Series is a one-dimensional array with indexed data. Let's create a Series from a Python list.

In [5]:
series = pd.Series([10, 20, 30, 40])
series

0    10
1    20
2    30
3    40
dtype: int64

## <font color = 'dodgerblue'>**Creating Pandas Dataframes**
A Dataframe is a two-dimensional array with flexible row indices and column names. Let's create a Dataframe from a dictionary.

In [6]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## <font color = 'dodgerblue'>**Basic Data Manipulation**
We can perform various operations like selecting, filtering, and sorting data. Let's explore some of these.

In [7]:
# Selecting a column
names = df['Name']

# Filtering data
filtered_df = df[df['Age'] > 30]

# Sorting data
sorted_df = df.sort_values('Age', ascending=False)

names, filtered_df, sorted_df

(0      Alice
 1        Bob
 2    Charlie
 Name: Name, dtype: object,       Name  Age     City
 2  Charlie   35  Chicago,       Name  Age         City
 2  Charlie   35      Chicago
 1      Bob   30  Los Angeles
 0    Alice   25     New York)

## <font color = 'dodgerblue'>**Using `loc` for Label-Based Indexing**
The `loc` method allows us to select rows and columns by label. Let's select the row with index label 1 and specific columns by their names.

In [8]:
# Selecting the row with index label 1 and columns 'Name' and 'Age'
selected_data_loc = df.loc[1, ['Name', 'Age']]
selected_data_loc

Name    Bob
Age      30
Name: 1, dtype: object

## <font color = 'dodgerblue'>**Using `iloc` for Integer-Based Indexing**
The `iloc` method allows us to select rows and columns by integer index. Let's select the second row (index 1) and the first two columns (indices 0 and 1).

In [9]:
# Selecting the second row and the first two columns by integer index
selected_data_iloc = df.iloc[1, [0, 1]]
selected_data_iloc

Name    Bob
Age      30
Name: 1, dtype: object

## <font color = 'dodgerblue'>**Interactive Exercise: Simple Data Analysis with Products Dataset** </font>
In this exercise, we'll perform some basic data analysis on a sample products dataset.

### Task
1. Load the `products.csv` file.
2. Explore the first few rows of the dataset.
3. Filter the products based on a specific category (e.g., 'Electronics').
4. Compute basic statistics like mean price and total quantity for the filtered category.
5. Get the mean price for each category

Let's start coding!

In [11]:
import pandas as pd

products = pd.read_csv('products.csv')

In [12]:
products.head()

  Product Name     Category  Price  Quantity
0       Laptop  Electronics    800        10
1        Chair    Furniture     50        20
2          Pen   Stationery      1       100
3        Phone  Electronics    300        15
4        Table    Furniture    100         5

In [13]:
elec_products = products[products['Category'] == 'Electronics']

In [14]:
elec_products

  Product Name     Category  Price  Quantity
0       Laptop  Electronics    800        10
3        Phone  Electronics    300        15

In [18]:
elec_products['Price'].mean() # mean

550.0

In [19]:
elec_products['Quantity'].sum() # total quantity

25

In [21]:
products.groupby('Category')['Price'].mean()

Category
Electronics    550.0
Furniture       75.0
Stationery       1.0
Name: Price, dtype: float64

### <font color = 'dodgerblue'>**Mount Google Drive**

In [46]:
# mount google drive
# so that we can save and load models/data from google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [47]:
# library to navigate file system
from pathlib import Path

In [48]:
# check current director
!pwd

/content

If we do not provide specific location, files are saved in current directory. When we close Google Colab, these files will be lost. Thus we should save files/models on google drive.

### <font color = 'dodgerblue'>**Specify the folder wherethe file is saved**

In [49]:
# here I have saved save my data to folder Data in my Google drive. /content/drive/MyDrive refers to
# path where google drive is mounted. /teaching_fall_2022 is folder in my Google drive.
# You should change this to folder you want to save data in your your Google drive

# specify pathlib folder
# This is a system Path(PosixPath)

data_folder = Path('/content/drive/MyDrive/teaching_fall_2023/ML/Lecture1_Python_Numpy_Pandas')

### <font color = 'dodgerblue'>**Complete the Task**

In [50]:
# Loading the products dataset from the CSV file
products_dataset = pd.read_csv(data_folder/'products.csv')
products_dataset

  Product Name     Category  Price  Quantity
0       Laptop  Electronics    800        10
1        Chair    Furniture     50        20
2          Pen   Stationery      1       100
3        Phone  Electronics    300        15
4        Table    Furniture    100         5

In [51]:
# Exploring the first few rows
first_rows = products_dataset.head()
first_rows

  Product Name     Category  Price  Quantity
0       Laptop  Electronics    800        10
1        Chair    Furniture     50        20
2          Pen   Stationery      1       100
3        Phone  Electronics    300        15
4        Table    Furniture    100         5

In [52]:
# Filtering products based on the 'Electronics' category
electronics_products = products_dataset[products_dataset['Category'] == 'Electronics']
electronics_products

  Product Name     Category  Price  Quantity
0       Laptop  Electronics    800        10
3        Phone  Electronics    300        15

In [53]:
# Computing basic statistics for the 'Electronics' category
mean_price_electronics = electronics_products['Price'].mean()
total_quantity_electronics = electronics_products['Quantity'].sum()

mean_price_electronics, total_quantity_electronics

(550.0, 25)

In [54]:
# Grouping by category and computing the mean price
category_mean_price = products_dataset.groupby('Category')['Price'].mean()

category_mean_price

Category
Electronics    550.0
Furniture       75.0
Stationery       1.0
Name: Price, dtype: float64

## <font color = 'dodgerblue'>**Pivot Tables**
Pivot tables provide a way to summarize data in a tabular form. Let's create a pivot table to analyze the mean price by category.

In [55]:
# Creating a pivot table
pivot_table = products_dataset.pivot_table(values='Price', index='Category', aggfunc='mean')
pivot_table

             Price
Category
Electronics    550
Furniture       75
Stationery       1

## <font color = 'dodgerblue'>**Merge Operations**
Merge operations allow us to combine datasets. Let's create a new DataFrame and merge it with our existing one.

In [56]:
# New DataFrame for merging
discounts = pd.DataFrame({
    'Category': ['Electronics', 'Furniture'],
    'Discount': [0.1, 0.05]
})

# Merging DataFrames
merged_df = pd.merge(products_dataset, discounts, on='Category', how='left')
merged_df

  Product Name     Category  Price  Quantity  Discount
0       Laptop  Electronics    800        10      0.10
1        Chair    Furniture     50        20      0.05
2          Pen   Stationery      1       100       NaN
3        Phone  Electronics    300        15      0.10
4        Table    Furniture    100         5      0.05

The `pd.merge` function is a powerful feature in Pandas that allows you to combine two DataFrames based on a common column or index. In the given code snippet, `merged_df = pd.merge(products_dataset, discounts, on='Category', how='left')`, two DataFrames (`products_dataset` and `discounts`) are being merged.

Here's a detailed explanation of the code:

### Parameters

- **`products_dataset`**: The first DataFrame to be merged. It presumably contains information about various products, including a 'Category' column.
- **`discounts`**: The second DataFrame to be merged. It should contain discount information for different categories, also including a 'Category' column.
- **`on='Category'`**: Specifies the common column ('Category') on which the two DataFrames will be merged. Both DataFrames must have a column with this name.
- **`how='left'`**: Specifies the type of merge to be performed. A 'left' merge includes all the rows from the first DataFrame (`products_dataset`) and the matched rows from the second DataFrame (`discounts`). If there's no match, the result will have `NaN` for the columns of the second DataFrame.

### Result

The `merged_df` DataFrame will contain all the columns from both `products_dataset` and `discounts`. Rows from `products_dataset` will be matched with rows from `discounts` based on the 'Category' column. If a category in `products_dataset` doesn't have a corresponding entry in `discounts`, the columns from `discounts` will be filled with `NaN` for that category.

## <font color = 'dodgerblue'>**Interactive Exercise: Advanced Data Analysis** with Products Dataset
In this exercise, we'll dive into advanced data analysis techniques using Pandas on a products dataset.

### Task 1: Load the Products Dataset
- Load the `products.csv` file into a DataFrame.
- Display the first 3 rows to understand the structure of the data.

### Task 2: Analyze Products by Category
- Group the products by the 'Category' column.
- Calculate the mean price and total quantity for each category.

### Task 3: Create a Pivot Table
- Create a pivot table to show the mean price of products for each category.

### Task 4: Merge Additional Data
- Assume you have a DataFrame `discounts` with discount information for some categories.
- Merge it with the products dataset using a left join on the 'Category' column.
- Calculate the final price after applying the discount.

Let's start coding!

In [22]:
products.head(3)

  Product Name     Category  Price  Quantity
0       Laptop  Electronics    800        10
1        Chair    Furniture     50        20
2          Pen   Stationery      1       100

In [24]:
cat = products.groupby('Category')

In [26]:
cat['Price'].mean()

Category
Electronics    550.0
Furniture       75.0
Stationery       1.0
Name: Price, dtype: float64

In [27]:
cat['Quantity'].sum()

Category
Electronics     25
Furniture       25
Stationery     100
Name: Quantity, dtype: int64

In [28]:
products.pivot_table(values='Price', index='Category', aggfunc='mean')

             Price
Category
Electronics    550
Furniture       75
Stationery       1

In [31]:
discounts = pd.DataFrame({
    'Category': ['Electronics', 'Furniture'],
    'Discount': [0.1, 0.05]
})

new_df = products.merge(discounts, on='Category', how='left')

new_df['Final Price'] = new_df['Price'] * (1-new_df['Discount'])

In [32]:
new_df

  Product Name     Category  Price  Quantity  Discount  Final Price
0       Laptop  Electronics    800        10      0.10        720.0
1        Chair    Furniture     50        20      0.05         47.5
2          Pen   Stationery      1       100       NaN          NaN
3        Phone  Electronics    300        15      0.10        270.0
4        Table    Furniture    100         5      0.05         95.0

In [57]:
# Task 1: Load the Products Dataset
products_dataset = pd.read_csv(data_folder/'products.csv')
products_dataset.head(3)

  Product Name     Category  Price  Quantity
0       Laptop  Electronics    800        10
1        Chair    Furniture     50        20
2          Pen   Stationery      1       100

In [62]:
# Task 2: Analyze Products by Category
category_analysis = products_dataset.groupby('Category').agg({'Price': 'mean', 'Quantity': 'sum'})
category_analysis

             Price  Quantity
Category
Electronics  550.0        25
Furniture     75.0        25
Stationery     1.0       100

In [63]:
# Task 3: Create a Pivot Table
pivot_table = products_dataset.pivot_table(values='Price', index='Category', aggfunc='mean')
pivot_table

             Price
Category
Electronics    550
Furniture       75
Stationery       1

In [60]:
# Task 4: Merge Additional Data (example discounts DataFrame)
discounts = pd.DataFrame({
    'Category': ['Electronics', 'Furniture'],
    'Discount': [0.1, 0.05]
})
merged_df = pd.merge(products_dataset, discounts, on='Category', how='left')
merged_df

  Product Name     Category  Price  Quantity  Discount
0       Laptop  Electronics    800        10      0.10
1        Chair    Furniture     50        20      0.05
2          Pen   Stationery      1       100       NaN
3        Phone  Electronics    300        15      0.10
4        Table    Furniture    100         5      0.05

In [61]:
merged_df['Final Price'] = merged_df['Price'] * (1 - merged_df['Discount'])
merged_df

  Product Name     Category  Price  Quantity  Discount  Final Price
0       Laptop  Electronics    800        10      0.10        720.0
1        Chair    Furniture     50        20      0.05         47.5
2          Pen   Stationery      1       100       NaN          NaN
3        Phone  Electronics    300        15      0.10        270.0
4        Table    Furniture    100         5      0.05         95.0